ALTER DATABASE FinRecover   
SET QUERY_STORE = ON;

ALTER DATABASE FinRecover   
SET QUERY_STORE (  
    OPERATION_MODE = READ_WRITE,  
    CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30),  
    DATA_FLUSH_INTERVAL_SECONDS = 900,  
    INTERVAL_LENGTH_MINUTES = 60,  
    MAX_STORAGE_SIZE_MB = 100,  
    QUERY_CAPTURE_MODE = AUTO
);
